### ISSUE TITLE
Integrate OBS Remote

### ISSUE THREAD

**Issue by dguenther** [The-Velvet-Room/web-overlay#1]
Pull in support for [OBS Remote](https://github.com/bilhamil/OBSRemote). This will allow scene control and overlay control from one interface. It should allow for complex transitions as well, such as using video or making a "BATTLE START!" scene with two characters facing each other.

**Comment by nswartz** [comment]
This is complete, yes?

**Comment by dguenther** [comment]
Did this get completed in your branch?

**Comment by nswartz** [comment]
We have had support for obs remote for awhile, but it's true that we handle the "battle start" and instant replays a different way at the moment. I would still call this done since it is all set up already.
