### ISSUE TITLE
Create a backup, less CPU intensive match intro

### ISSUE THREAD

**Issue by Camtendo** [The-Velvet-Room/web-overlay#119]
For instances where we don't have the luxury of a godly CPU, we should display a more subtle match intro. We could do a Street Fighter 4 style without abusing jQuery animations.

**Comment by nswartz** [comment]
I plan to use GSAP (which is pure JS and utilized requestAnimationFrame) to remedy this at some point in the future. I would expect this to provide a smoother animation (the current one can lag sometimes) and be more efficient overall.

**Comment by dguenther** [comment]
:+1: Make it so.

**Comment by Camtendo** [comment]
Didn't this get fixed?

**Comment by nswartz** [comment]
This is done. It definitely looks a lot smoother to me, at least compared to the old one.
