### ISSUE TITLE
Top 8 display doesn't work on certain bracket sizes

### ISSUE THREAD

**Issue by dguenther** [The-Velvet-Room/web-overlay#138]
We hotfixed this a few times to get us through SoDak, but we should fix this properly. Right now we're trying to use math to determine which round starts top 8, but I think it might be easier to find the latest round and then subtract a fixed amount from that. It'd be a bit slower, but we normally won't be dealing with large numbers of matches.

**Comment by Camtendo** [comment]
Another thing of note (Datrick brought this up several times at MSK: FGC) is that Grand Finals Reset currently shows up regardless of if it's actually necessary.
